### ISSUE TITLE
[Skeleton] Cannot read property 'gray' of undefined

### ISSUE THREAD

**Issue by clngkusnd** [chakra-ui/chakra-ui#1214]
I can't use the Skeleton component. Here's the error message:

```
TypeError: Cannot read property 'gray' of undefined
    at Skeleton (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:9973:19)
    at renderWithHooks (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:167090:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:169769:13)
    at beginWork (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:170883:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:152475:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:152524:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:152579:31)
    at beginWork$1 (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:175490:7)
    at performUnitOfWork (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:174441:12)
    at workLoopSync (http://localhost:6006/vendors~main.b8048b8e3cecc2277bc3.bundle.js:174417:22)
```

**Comment by with-heart** [comment]
Any way you could create a CodeSandbox reproduction for us? It's hard to say what's causing this issue without being able to see your setup.

**Comment by segunadebayo** [comment]
@with-heart Please re-open this once we have a valid reproduction.
