### ISSUE TITLE
Getting an Error with SSR after most recent update

### ISSUE THREAD

**Issue by chuckstock** [chakra-ui/chakra-ui#131]
After the most recent update I'm getting this error:
```
regeneratorRuntime is not defined
ReferenceError: regeneratorRuntime is not defined
    at /sandbox/node_modules/@react-spring/core/index.cjs.js:635:5
    at /sandbox/node_modules/@react-spring/core/index.cjs.js:687:4
    at Object.<anonymous> (/sandbox/node_modules/@react-spring/core/index.cjs.js:1203:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/@react-spring/web/index.cjs.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
Here is a fresh codesandbox and it happens with Nextjs in just a vanilla example.
https://codesandbox.io/embed/hello-world-49rmf

**Comment by jorgenho** [comment]
I found a workaround for this issue: 

add `@babel/plugin-transform-runtime`  as a dev dependency, and import it in your _app.js file:

`import 'regenerator-runtime/runtime';`

[https://babeljs.io/docs/en/babel-polyfill](https://babeljs.io/docs/en/babel-polyfill)

**Comment by harshzalavadiya** [comment]
> I found a workaround for this issue:
> 
> add `@babel/plugin-transform-runtime` as a dev dependency, and import it in your _app.js file:
> 
> `import 'regenerator-runtime/runtime';`
> 
> https://babeljs.io/docs/en/babel-polyfill

Can confirm works!
I guess issue is coming from `react-spring` using 9.x if you lock version at `react-spring@8.0.27` also worked for me
```json
"resolutions": {
  "react-spring": "8.0.27"
}
```

**Comment by chuckstock** [comment]
Great thank you @jorgenho and @harshzalavadiya!

**Comment by esteladiaz** [comment]
Hello, can someone expand on how to use _app.js with ` import 'regenerator-runtime/runtime';`?

**Comment by harshzalavadiya** [comment]
@esteladiaz Not sure if I understand correctly but if you mean how to then checkout next documentation on `_app` at https://nextjs.org/docs/advanced-features/custom-app and copy` _app.js ` and add import on top
