### ISSUE TITLE
@chakra-ui/theme not working with v1

### ISSUE THREAD

**Issue by thomasthiebaud** [chakra-ui/chakra-ui#1498]
With this dependencies

```
    "@chakra-ui/core": "^1.0.0-rc.0",
    "@chakra-ui/theme": "^1.0.0-next.3",
    "@chakra-ui/theme-tools": "^1.0.0-next.3",
```

that code

```
import { ChakraProvider, CSSReset } from "@chakra-ui/core";
import theme from "@chakra-ui/theme";

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => (
  <ChakraProvider theme={theme}>
    <CSSReset />
    <Component {...pageProps} />
  </ChakraProvider>
);

export default MyApp;
```

returns

```
TypeError: breakpoints.map is not a function
    at /.../node_modules/@chakra-ui/styled-system/dist/cjs/css.js:31:50
    at /.../node_modules/@chakra-ui/styled-system/dist/cjs/css.js:78:41
    at styles (/.../node_modules/@chakra-ui/system/dist/cjs/providers.js:86:9)
    at Object.children (/.../node_modules/@emotion/core/dist/core.cjs.dev.js:239:51)
    at ReactDOMServerRenderer.render (/.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3635:55)
    at ReactDOMServerRenderer.read (/.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at Object.renderPage (/.../node_modules/next/dist/next-server/server/render.js:45:686)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:129:19)
    at loadGetInitialProps (/.../node_modules/next/dist/next-server/lib/utils.js:5:101)
```

If I copy the default theme using 

```
npx chakra-cli init --theme --ts
```

and modify `breakpoints.ts` to export an array instead of an object it works

**Comment by ljosberinn** [comment]
hi @thomasthiebaud please update `@theme` and `@theme-tools` to `rc.0` too. The CLI is deprecated for now.

**Comment by thomasthiebaud** [comment]
Awesome, that solves my issue
