### ISSUE TITLE
[CSSReset] Error: Could not parse CSS stylesheet

### ISSUE THREAD

**Issue by wKovacs64** [chakra-ui/chakra-ui#161]
There is an issue with some versions of [`jsdom`](https://github.com/jsdom/jsdom) where CSS comments (`/* ... */`) are not parsed correctly. I am attempting to leverage Chakra UI in an environment where I don't have control over the `jsdom` version (a `jest` dependency) and using the `CSSReset` component triggers this bug due to the comments in [`preflight.js`](https://github.com/chakra-ui/chakra-ui/blob/27cbdb9ae78ae54a3edab8a5304e0e95de2d9a5f/packages/chakra-ui/src/CSSReset/preflight.js):

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
  Error: Could not parse CSS stylesheet
      at exports.createStylesheet (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:35:21)
      at HTMLStyleElementImpl._updateAStyleBlock (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:67:5)
      at HTMLStyleElementImpl._childTextContentChangeSteps (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:36:12)
      at HTMLStyleElementImpl.insertBefore (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:214:14)
      at HTMLStyleElementImpl.appendChild (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:316:17)
      at HTMLStyleElement.appendChild (C:\dev\sa\node_modules\jsdom\lib\jsdom\living\generated\Node.js:283:45)
      at StyleSheet.insert (C:\dev\sa\node_modules\@emotion\sheet\dist\sheet.cjs.dev.js:121:11)
      at toSheet (C:\dev\sa\node_modules\@emotion\cache\dist\cache.cjs.dev.js:19:19)
      at Array.forEach (<anonymous>)
      at Function.ruleSheet (C:\dev\sa\node_modules\@emotion\cache\dist\cache.cjs.dev.js:81:31) {/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */}
```

Any thoughts on whether or not this can/should be addressed at the Chakra UI level? We could simply remove the comments from `preflight.js`, but I didn't want to open a PR for that without discussing it first.

Thanks.

**Comment by segunadebayo** [comment]
Hi Justin,

If you're sure that the comments in `preflight.js` are the issue, kindly remove the comments and submit a PR.

Thank you.

**Comment by wKovacs64** [comment]
@all-contributors please add @wKovacs64 for code

**Comment by aaronmcadam** [comment]
Ah, I wondered what was causing that! Thanks @wKovacs64!
