### ISSUE TITLE
Drawer component – enableBodyScroll/disableBodyScroll failing.

### ISSUE THREAD

**Issue by neil-morgan** [chakra-ui/chakra-ui#2281]
# The scroll lock functions do not work when opening/closing the Drawer.

When opening/closing the Drawer component the respective enableBodyScroll/disableBodyScroll does not work. The Drawer opens and closes correctly but the document remains scrollable and the scrollbar remains visible.

Errors took from the browser console.

```
index.js:1 disableBodyScroll unsuccessful - targetElement must be provided when calling disableBodyScroll on IOS devices. 
    at Modal (http://localhost:3000/static/js/1.chunk.js:7776:22)
    at Spring (http://localhost:3000/static/js/1.chunk.js:63907:35)
    at KeyframesImpl (http://localhost:3000/static/js/1.chunk.js:64162:39)
    at Transition (http://localhost:3000/static/js/1.chunk.js:64376:34)
    at Slide (http://localhost:3000/static/js/1.chunk.js:12747:20)
    at Drawer (http://localhost:3000/static/js/1.chunk.js:4392:21)
    at UseDrawer (http://localhost:3000/static/js/main.chunk.js:2500:76)
    at div
    at render
    at http://localhost:3000/static/js/1.chunk.js:4795:20
    at Col (http://localhost:3000/static/js/main.chunk.js:879:23)
    at div
    at render
    at http://localhost:3000/static/js/1.chunk.js:4795:20
    at Row (http://localhost:3000/static/js/main.chunk.js:876:13)
    at div
    at render
    at Container (http://localhost:3000/static/js/main.chunk.js:848:76)
    at header
    at render
    at SidebarProvider (http://localhost:3000/static/js/main.chunk.js:1339:3)
    at ThemeProvider
    at ThemeProvider (http://localhost:3000/static/js/1.chunk.js:12305:20)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2273
disableBodyScroll @ bodyScrollLock.esm.js:126
(anonymous) @ index.js:123
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168

index.js:1 enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices. 
    at Transition (http://localhost:3000/static/js/1.chunk.js:64376:34)
    at Slide (http://localhost:3000/static/js/1.chunk.js:12747:20)
    at Drawer (http://localhost:3000/static/js/1.chunk.js:4392:21)
    at UseDrawer (http://localhost:3000/static/js/main.chunk.js:2500:76)
    at div
    at render
    at http://localhost:3000/static/js/1.chunk.js:4795:20
    at Col (http://localhost:3000/static/js/main.chunk.js:879:23)
    at div
    at render
    at http://localhost:3000/static/js/1.chunk.js:4795:20
    at Row (http://localhost:3000/static/js/main.chunk.js:876:13)
    at div
    at render
    at Container (http://localhost:3000/static/js/main.chunk.js:848:76)
    at header
    at render
    at SidebarProvider (http://localhost:3000/static/js/main.chunk.js:1339:3)
    at ThemeProvider
    at ThemeProvider (http://localhost:3000/static/js/1.chunk.js:12305:20)
```

## Dependencies

```
  "dependencies": {
    "@chakra-ui/core": "^0.8.0",
    "@chakra-ui/css-reset": "^1.0.0-next.3",
    "@emotion/core": "^10.0.35",
    "@emotion/styled": "^10.0.27",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "emotion-theming": "^10.0.27",
    "focus-visible": "^5.1.0",
    "polished": "^3.6.5",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
```

**Comment by ljosberinn** [comment]
see #781, closing in favor

**Comment by ljosberinn** [comment]
oh and ince I just saw that: you're mixing versions. Please do not mix v1 with v0 - remove the `css-reset` package json entry OR migrate to v1 entirely. Else you'll end up with hard to debug errors.

**Comment by diogolessa** [comment]
> see #781, closing in favor

Sorry, but are those related problems? I am also facing the `enableBodyScroll/disableBodyScroll` issue. Dependencies:
 ```
    "@chakra-ui/core": "^0.8.0",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@react-google-maps/api": "^1.9.7",
    "cookie": "^0.4.1",
    "currency.js": "^2.0.0",
    "dayjs": "^1.8.29",
    "deepmerge": "^4.2.2",
    "emotion": "^10.0.27",
    "emotion-server": "^10.0.27",
    "emotion-theming": "^10.0.27",
    "jwt-decode": "^2.2.0",
    "memoize-one": "^5.1.1",
    "next": "9.5.4",
    "next-seo": "^4.5.0",
    "nprogress": "^0.2.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hook-form": "^5.7.2",
    "react-multi-carousel": "^2.5.5",
    "react-number-format": "^4.4.1",
    "react-table": "^7.2.2",
    "slugify": "^1.4.0",
    "swiper": "^5.4.3",
    "swr": "^0.3.0",
    "throttle-debounce": "^2.2.1",
    "use-smooth-scroll": "^1.1.1"
```

**Comment by ljosberinn** [comment]
sorry, I must've linked the wrong issue, that's silly!

@diogolessa I'd heavily recommend moving to v1 as v0 will very most likely not see further releases as we near the final v1 release
