### ISSUE TITLE
Can't run storybook in fresh clone of chakra-ui

### ISSUE THREAD

**Issue by rpadilla6** [chakra-ui/chakra-ui#2488]
# Bug report
Can't get storybook to run in chakra ui repo. I was trying to troubleshoot why I couldn't get storybook to load the theme provider in another project I'm doing. Might have to use v0.8 for now until this gets fixed, they may not be related though.

## Describe the bug
Error complains about not being able to find @chakra-ui/babel-plugin.

## To reproduce

1. run `git clone git@github.com:chakra-ui/chakra-ui.git`
2. `cd chakra-ui`
3. `yarn prestart`
4. `yarn storybook`
5. get following error:
```
ERROR in ./.storybook/generated-refs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@chakra-ui/babel-plugin' from '/Users/ryanpadilla/Projects/chakra-ui'
    at Function.resolveSync [as sync] (/Users/ryanpadilla/Projects/chakra-ui/node_modules/resolve/lib/sync.js:90:15)
    at resolveStandardizedName (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:415:26)
    at /Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/Users/ryanpadilla/Projects/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:97:27)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js storybook-addon-performance/register ./node_modules/@storybook/addon-a11y/dist/register.js ./.storybook/generated-refs.js main[4]
```
## System information

- OS: macOs
- Browser: chrome
- Version of @chakra-ui/react: v1.0
- Version of Node.js: 14.8.0

**Comment by rpadilla6** [comment]
...and right after I post this I read through the scripts in `package.json` and realized `yarn storybook` came after `yarn build` in the `yarn start` command. Just needed to build everything, seems to still work fine. I'm still trying to troubleshoot why components aren't getting styled correctly in storybook in my other project, but I'll close this issue since it's resolved.

**Comment by AndrewPrifer** [comment]
I have the same issue of styles not being applied in storybook for chakra 1.0.0 (1.0.0.rc8 works fine).

**Comment by hutber** [comment]
Related: https://github.com/chakra-ui/chakra-ui/issues/2527
