### ISSUE TITLE
useBreakpointValue breaks MS Edge

### ISSUE THREAD

**Issue by ssijak** [chakra-ui/chakra-ui#2615]
# Bug report

## Describe the bug

useBreakpointValue breaks MS Edge

## To reproduce

If I try to use useBreakpointValue hook in my nextjs project it breaks the website in ms edge, all JS stops executing after it encounters the hook.

It breaks with ```SCRIPT438: SCRIPT438: Object doesn't support property or method 'endsWith'```

I've tried to polyfill with ```import "core-js/features/string/ends-with"; ``` and in several other ways per nextjs docs, but it did not help.

## Minimal reproduction

https://codesandbox.io/s/gracious-waterfall-dt01w?file=/src/index.js

## System information

- OS: Windows 10
- Browser (if applies): MS Edge
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: 12

**Comment by with-heart** [comment]
This is interesting. Edge should theoretically support `endsWith`, so it's strange that this is causing an issue. We use `endsWith` in a single place in the codebase: https://github.com/chakra-ui/chakra-ui/blob/dd5a4974db93d080a6603b3c1ca2c2b91f5136d9/packages/media-query/src/create-media-query.ts#L86-L86

I'm not sure why this would cause a failure for Edge though. @ssijak could you try the solution [in this comment on the `next.js` repo](https://github.com/vercel/next.js/issues/7993#issuecomment-537530895) and see if it resolves your issue?

**Comment by gitmonster** [comment]
I have the same issue on Edge Legacy with a NextJS Project and applied the polyfill the way @with-heart 
mentions. Nothing helps.

**Comment by ssijak** [comment]
@with-heart I've tried that, and several other solutions and nothing worked for MS Edge. It feels strange, it should work, but it keeps fatally breaking with that error.

Even doing (taken from [mozzila docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)) :
```js
if (!String.prototype.endsWith) {
  String.prototype.endsWith = function(search, this_len) {
    if (this_len === undefined || this_len > this.length) {
      this_len = this.length;
    }
    return this.substring(this_len - search.length, this_len) === search;
  };
}
```

Before calling the hook does not help. Either I'm missing something obvious or there is some weird thing happening with my Edge.

**Comment by gitmonster** [comment]
Has anyone a solution?

**Comment by objmj-itminds** [comment]
I, too, have stumbled into this issue.

looking at it 

```
TypeError: value.endsWith is not a function
    at subtract (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:78:44)
    at createMediaQueryString (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:55:43)
    at ~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:23:17
    at Array.map (<anonymous>)
    at createMediaQueries (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:16:6)
    at ~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint.js:32:45
    at Object.useMemo (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:1582:19)
    at Object.useMemo (~\node_modules\react\cjs\react.development.js:1532:21)
    at useBreakpoint (~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint.js:31:40)
    at useBreakpointValue (~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint-value.js:22:53)
    at LayoutDesktop (~\.next\server\pages\_app.js:4503:98)
    at processChild (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
 ```
 
 To be a bit debuggy I tried adding the following code: 
 
 ```javascript
 function subtract(value) {
  console.log("subtract value", typeof value, value)
  if (typeof value === 'function') {
    const what = value(); // new line 80 
    console.log("WHAT IS THIS?", what)
    return calculateMeasurement(what)
  }

  return calculateMeasurement(value, value.endsWith("px") ? -1 : -0.01);
}
``` 
 
Which interestingly provided me with a new stack trace:
 
 ```
 TypeError: thisArg.reduce is not a function
    at Array.reduceAsync (~\node_modules\ts-array-ext\reduceAsync\index.js:11:26)
    at ~\node_modules\@chakra-ui\react\dist\cjs\extend-theme.js:25:34
    at subtract (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:80:18)
    at createMediaQueryString (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:55:43)
    at ~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:23:17
    at Array.map (<anonymous>)
    at createMediaQueries (~\node_modules\@chakra-ui\media-query\dist\cjs\create-media-query.js:16:6)
    at ~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint.js:32:45
    at Object.useMemo (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:1582:19)
    at Object.useMemo (~\node_modules\react\cjs\react.development.js:1532:21)
    at useBreakpoint (~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint.js:31:40)
    at useBreakpointValue (~\node_modules\@chakra-ui\media-query\dist\cjs\use-breakpoint-value.js:22:53)
    at LayoutDesktop (~\.next\server\pages\_app.js:4503:98)
    at processChild (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (~\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
 ```
 It seems that somehow another dependency's function got passed down into `create-media-query` as the `value.`
 
 After removing this dependency, I haven't seen this issue again. Can't tell what happened or how a loose import caused such a huge issue.

**Comment by mgranderath** [comment]
I also just encountered the issue and found out that I have a polyfill that added two functions (`flat` and `flatMap`) to the `breakpoints` array that gets retrieved from the theme. This then causes the above seen error because they are assumed to be strings. For now I am using `patch-package` to patch the `createMediaQueries()` method to filter out anything that is not a string. I'm not sure yet whether it is Babel or some other polyfill.
