### ISSUE TITLE
[Popover] jest show error message

### ISSUE THREAD

**Issue by max10rogerio** [chakra-ui/chakra-ui#2684]
# Bug report

When I write a test of a component that uses Popover, my jest test show me an error log and I need call a async find in any component

> Show error on terminal
```typescript
import React from 'react'

import HomePage from '.'
import { renderWithProviders } from '@utils/test-utils'

describe('Render Home Page with correct buttons', () => {
  it('should render', () => {
    const renderResult = renderWithProviders(<HomePage />)

    expect(renderResult).toBeTruthy()
  })
})

```

> Supress error on terminal
```typescript
import React from 'react'

import HomePage from '.'
import { renderWithProviders } from '@utils/test-utils'

describe('Render Home Page with correct buttons', () => {
  it('should render', async () => {
    const renderResult = renderWithProviders(<HomePage />)

    expect(await renderResult.findAllByTestId('button')).toBeTruthy()
  })
})

```

> Error log
```log
console.error
      Warning: An update to Popover inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at Popover (/home/max/dev/b2b/doom/node_modules/@chakra-ui/popover/src/popover.tsx:72:18)
          at GUserMenu (/home/max/dev/b2b/doom/src/components/g-user-menu/g-user-menu.tsx:39:16)
          at div
          at Styled(div) (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:35:23)
          at div
          at Styled(div) (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:35:23)
          at Flex (/home/max/dev/b2b/doom/node_modules/@chakra-ui/layout/src/flex.tsx:66:5)
          at div
          at Styled(div) (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:35:23)
          at GContainer (/home/max/dev/b2b/doom/src/components/g-container/g-container.tsx:4:40)
          at header
          at Styled(div) (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:35:23)
          at Flex (/home/max/dev/b2b/doom/node_modules/@chakra-ui/layout/src/flex.tsx:66:5)
          at GHeader
          at div
          at Styled(div) (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:35:23)
          at Flex (/home/max/dev/b2b/doom/node_modules/@chakra-ui/layout/src/flex.tsx:66:5)
          at MainLayout (/home/max/dev/b2b/doom/src/layouts/main-layout.tsx:6:33)
          at HomePage
          at Object.<anonymous>.exports.ThemeProvider (/home/max/dev/b2b/doom/node_modules/styled-components/src/models/ServerStyleSheet.js:66:13)
          at ColorModeProvider (/home/max/dev/b2b/doom/node_modules/@chakra-ui/color-mode/src/color-mode-provider.tsx:56:5)
          at ThemeProvider (/home/max/dev/b2b/doom/node_modules/@emotion/react/dist/emotion-element-1eecae82.cjs.dev.js:93:21)
          at ChakraProvider (/home/max/dev/b2b/doom/node_modules/@chakra-ui/react/src/chakra-provider.tsx:49:5)
          at ThemeWrapper (/home/max/dev/b2b/doom/src/components/theme/theme.tsx:6:42)
          at Provider (/home/max/dev/b2b/doom/node_modules/react-redux/lib/components/Provider.js:19:20)
          at wrapper (/home/max/dev/b2b/doom/src/utils/test-utils.tsx:17:32)

      at printWarning (../node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (../node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (../node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at setStyles (../node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at fn (../node_modules/@chakra-ui/popper/src/react-popper.ts:73:9)
      at Object.forceUpdate (../node_modules/@chakra-ui/popper/node_modules/@popperjs/core/src/index.js:233:21)
      at ../node_modules/@chakra-ui/popper/node_modules/@popperjs/core/src/index.js:243:22
```

## To reproduce

1. Create a component with Popover
2. Create a test that render this component
3. Run jest test and see error on terminal

## Expected behavior

Not show a error log

## System information
- Version of @chakra-ui/react:1.0.1
- Version of Node.js: 14.15.0

**Comment by afonsoduarte** [comment]
If you have a look at the Popover own tests, you can see that they are `async` and the first `expect` is wrapped in a `waitFor`: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/popover/tests/popover.test.tsx

So I believe what you are seeing is the expected behaviour.

**Comment by ljosberinn** [comment]
The test must be async to be able to use waitFor because the appearance of the popover is async due to popper internals. The error you're seeing in the test is most likely the same we also see which is unavoidable due to popper internals. Effectively it's out of our control.

**Comment by cloud-walker** [comment]
Hi guys, after experimenting a bit I've found that I can just mock away the `createPopper` function from `@popperjs/core` (used by chakra under the hood):

```javascript
// "__mocks__/@popperjs/core.js"
const noop = () => {}

/**
 * Chakra UI uses popperjs under the hood to handle popover positioning
 * we want to ignore this stuff in our tests as it causes a stupid
 * "act" warning and we will not test CSS stuff anyway...
 */
export const createPopper = () => {
  return {forceUpdate: noop, destroy: noop, state: null}
}
```

Cheers!

**Comment by builtbyjay** [comment]
Oh my goodness this just drove me mad for 3 straight hours. Thank you @cloud-walker for posting your solution!

**Comment by leoparis89** [comment]
> Hi guys, after experimenting a bit I've found that I can just mock away the `createPopper` function from `@popperjs/core` (used by chakra under the hood):
> 
> ```js
> // "__mocks__/@popperjs/core.js"
> const noop = () => {}
> 
> /**
>  * Chakra UI uses popperjs under the hood to handle popover positioning
>  * we want to ignore this stuff in our tests as it causes a stupid
>  * "act" warning and we will not test CSS stuff anyway...
>  */
> export const createPopper = () => {
>   return {state: null, forceUpdate: noop, destroy: noop, setOptions: noop}
> }
> ```
> 
> Cheers!

Still getting the warning with this
