### ISSUE TITLE
Upgrading to 1.0.4 gives: Error: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` when using `next build`

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2825]
I have just upgraded from 1.0.0 > 1.0.4 and when doing `next build` I recieve the following error:
```sh
Error occurred prerendering page "/blog/products/skincare/vitamin-c". Read more: https://err.sh/next.js/prerender-error
Error: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
    at useContext (/var/www/bp/frontend/node_modules/@chakra-ui/utils/dist/cjs/react-helpers.js:40:13)
    at Object.render (/var/www/bp/frontend/node_modules/@chakra-ui/layout/dist/cjs/list.js:106:38)
    at a.b.render (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:194)
    at a.b.read (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/var/www/bp/frontend/node_modules/next/dist/next-server/server/render.js:52:851)
    at Function.getInitialProps (/var/www/bp/frontend/.next/server/pages/_document.js:295:19)
    at loadGetInitialProps (/var/www/bp/frontend/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/var/www/bp/frontend/node_modules/next/dist/next-server/server/render.js:52:1142)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

its unclear to me what is causing this. I believe we need to use StylesProvider as suggested here, https://chakra-ui.com/docs/theming/component-style but this was working in 1.0.0.

# _app.tsx

```
const appTheme = {
  styles,
  breakpoints,
  colors,
  components,
  ...fonts,
}
export const theme = extendTheme(appTheme)


export default function App({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <ChakraProvider resetCSS theme={theme}>
      <Component {...pageProps} />
    </ChakraProvider>
  )
```

I could not create a codepen for this, but here is my whole lengthy dependencies:
```
"dependencies": {
    "@chakra-ui/react": "^1.0.4",
    "@chakra-ui/theme-tools": "^1.0.2",
    "@contentful/rich-text-react-renderer": "^14.1.1",
    "@contentful/rich-text-types": "^14.1.1",
    "@emotion/react": "^11.0.0",
    "@emotion/styled": "^11.0.0",
    "@zeit/next-source-maps": "^0.0.4-canary.
    "next": "^10.0.2",
    "next-compose-plugins": "^2.2.0",
    "next-pwa": "^5.0.0",
    "next-seo": "^4.17.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
  },
```

**Comment by with-heart** [comment]
Thanks for reporting this. I'm trying to think of any components that were previously un-themed/directly themed but now require that they're wrapped by a component that renders `StylesProvider`. 

cc: @chakra-ui/react-team Can yall think of anything?

**Comment by hutber** [comment]
Thanks, I am trying to go through and remove all components to narrow it down.

**Comment by jmiazga** [comment]
Are you using `FormLabel`, `FormErrorMessage`, or `FormHelperText` that arent nested in a `FormControl`?

**Comment by with-heart** [comment]
@jmiazga I had thought of that since we've been facing that one recently at work, but they would have already been broken in 1.0.0 I think.

**Comment by hutber** [comment]
We did have removed `FormControl` and `FormLabel` and ran the build and everything worked. I'll try to see which one is causing the issue.

**Comment by hutber** [comment]
Thanks guys, we did have 2 of these components and I have removed these, but we still see the error it seems to be there:

Version `1.0.4` 
```
[====] info  - Generating static pages (0/77)
Error occurred prerendering page "/blog/insights/the-truth-about-retinol". Read more: https://err.sh/next.js/prerender-error
Error: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
    at useContext (/var/www/bp/frontend/node_modules/@chakra-ui/utils/dist/cjs/react-helpers.js:40:13)
    at Object.render (/var/www/bp/frontend/node_modules/@chakra-ui/layout/dist/cjs/list.js:106:38)
    at a.b.render (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:194)
    at a.b.read (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/var/www/bp/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/var/www/bp/frontend/node_modules/next/dist/next-server/server/render.js:52:851)
    at Function.getInitialProps (/var/www/bp/frontend/.next/server/pages/_document.js:295:19)
    at loadGetInitialProps (/var/www/bp/frontend/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/var/www/bp/frontend/node_modules/next/dist/next-server/server/render.js:52:1142)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
version `1.0.0` successfully built:
```
> [PWA] Service worker: /var/www/bp/frontend/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (77/77)
info  - Finalizing page optimization  
```

**Comment by hutber** [comment]
We have narrowed down the issue guys, I believe this is completely our fault, but I thought I would say:
We were missing the ` <UnorderedList>` when we rendered, so the fix was as follows:

        <UnorderedList>
          <ListItem listStyleType='"- "'>{children}</ListItem>
        </UnorderedList>

**Comment by with-heart** [comment]
@hutber Glad to hear you got it working!

**Comment by jgrancher** [comment]
I had the same issue after upgrading `@chakra-ui/react` from 1.0 to 1.4. Turns out that I had a bunch of:

```jsx
<Flex as"ul">
  <ListItem>{...}</ListItem>
</Flex>
```

Swapping the `Flex` wrapper for an `UnorderedList` seemed to have fixed it... But I wish the error was more explicit! Thanks @hutber! 🙏
