### ISSUE TITLE
Using Chakra UI for a page that is rendered inside an iframe crashes the site

### ISSUE THREAD

**Issue by burhanuday** [chakra-ui/chakra-ui#3202]
# 🐛 Bug report

> Using Chakra UI for a page that is rendered inside an iframe crashes the site since Chakra UI is not able to access localstorage which is required for Color Mode

## 💥 Steps to reproduce

1. Setup a simple NextJS project and add Chakra UI to it
2. Try to embed a page of this project inside an iframe

## 🧐 Expected behavior

> Page does not crash

## 🧭 Possible Solution

> If the page is inside an iframe, a method to tell Chakra to not try to access localstorage

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.0.4          |
| Browser          | Chromium           |
| Operating System | Linux           |

## 📝 Additional information
Here's the stack trace
```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Call Stack
Object.get
./node_modules/@chakra-ui/color-mode/dist/esm/storage-manager.js (13:0)
eval
./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js (61:77)
invokePassiveEffectCreate
./node_modules/react-dom/cjs/react-dom.development.js (23487:0)
HTMLUnknownElement.callCallback
./node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
./node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
./node_modules/react-dom/cjs/react-dom.development.js (4056:0)
flushPassiveEffectsImpl
./node_modules/react-dom/cjs/react-dom.development.js (23574:0)
unstable_runWithPriority
./node_modules/scheduler/cjs/scheduler.development.js (646:0)
runWithPriority$1
./node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushPassiveEffects
./node_modules/react-dom/cjs/react-dom.development.js (23447:0)
eval
./node_modules/react-dom/cjs/react-dom.development.js (23324:0)
workLoop
./node_modules/scheduler/cjs/scheduler.development.js (590:0)
flushWork
.node_modules/scheduler/cjs/scheduler.development.js (545:0)
MessagePort.performWorkUntilDeadline
./node_modules/scheduler/cjs/scheduler.development.js (157:0)
```

**Comment by burhanuday** [comment]
Additional logs from browser console

storage-manager.js
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/storage-manager.js:17:29)
    at eval (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:73:213)
    at invokePassiveEffectCreate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23482:20)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23569:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:646:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23442:14)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23319:11)
    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:590:34)
    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:545:16)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:157:27)
```

```
The above error occurred in the <ColorModeProvider> component:

    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:46:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:78:71)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/react/dist/esm/chakra-provider.js:21:5)
    at MyApp (webpack-internal:///./pages/_app.js:48:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:150:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:639:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:764:24)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by burhanuday** [comment]
A temporary workaround
Setting colorModeManager to an empty function prevents Chakra from trying to access localstorage. But i think that this comes at the cost of being able to change the color mode
```
  <ChakraProvider colorModeManager={() => {}} >
       // ...
    </ChakraProvider>
```
