### ISSUE TITLE
When using multiple sliders at once, the "onChangeEvent" is called when it shouldn't

### ISSUE THREAD

**Issue by Treycos** [chakra-ui/chakra-ui#3522]
# 🐛 Bug report

The "onChangeEnd" event of the sliders is being called whenever the component re-renders when there are multiple sliders.

The function are usually called 

## 💥 Steps to reproduce

1. Create a component with multiple sliders
2. Bind all "onChangeEnd" event to a function that changes a state value
3. Move and release any slider thumb
4. The function is called by all sliders at once

## 💻 Link to reproduction

The CodeSandbox doesn't seem to compile at all for a reason I don't understand : https://codesandbox.io/s/loving-shadow-0d2ke?file=/src/Test.tsx

![screen-capture (11)](https://user-images.githubusercontent.com/19551067/110300815-a82b6d00-7ff7-11eb-9597-e8552c06b94c.gif)

Minimal code:

```
.sliders {
    display: flex;
    justify-content: space-around;
}
```

```
function Test() {
    const [state, setstate] = useState(1);

    const onDrag = useCallback(
        (id: number, start: boolean) => (value: number) => {
            console.log(id, start ? 'change start' : 'change end', value);
            setstate(id);
        },
        []
    );

    console.log('re-render');

    return (
        <div className='sliders'>
            <Slider
                orientation='vertical'
                onChangeStart={onDrag(1, true)}
                onChangeEnd={onDrag(1, false)}
                minH={90}
            >
                <SliderTrack>
                    <SliderFilledTrack />
                </SliderTrack>
                <SliderThumb  />
            </Slider>
            <Slider
                orientation='vertical'
                onChangeStart={onDrag(2, true)}
                onChangeEnd={onDrag(2, false)}
                minH={90}
            >
                <SliderTrack>
                    <SliderFilledTrack />
                </SliderTrack>
                <SliderThumb/>
            </Slider>
            <Slider
                orientation='vertical'
                onChangeStart={onDrag(3, true)}
                onChangeEnd={onDrag(3, false)}
                minH={90}
            >
                <SliderTrack>
                    <SliderFilledTrack />
                </SliderTrack>
                <SliderThumb />
            </Slider>
        </div>
    );
}
```

## 🧐 Expected behavior

The event should only be called once by the component that was used

Re-rendering a slider shouldn't trigger the "onChangeEnd" event

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.3.2 / 1.3.4      |
| Browser          |     Chrome / Firefox       |
| Operating System |     Windows 10       |

**Comment by matt-dale** [comment]
I was having a similar issue in my app (and same CodeSandbox compile issue) so I made this example [https://stackblitz.com/edit/multi-slider-example?file=src/App.js](https://stackblitz.com/edit/multi-slider-example?file=src/App.js). 
An obviously contrived and inefficient example, but shows that the `onChangeEnd` function is being called on the slider that was not moved.  
Move one slider, and watch the other slider's "saved" value change to 50.

**Comment by lonk** [comment]
Similar issue on our side with onChangeEnd, which is trapping us in an infinite loop

**Comment by konahart** [comment]
I have been experiencing similar behavior. I have found a workaround:
1) use a null useState, and set value to `{sliderValue ?? value}`
2) wrap `onChangeEnd` in a check that the value has actually changed: `if (val != value) {onChangeEndFunction(slider, val)}`

Demonstrating with @matt-dale's example:
```
function SliderWithHandlers(props) {
  const { onChangeEndFunction, value, slider } = props;
  const [sliderValue, setSliderValue] = useState(null);
  return (
    <Box>
      <Text as="h2">My "saved" value is: {value}</Text>
      <FormControl display="flex" alignItems="center">
        <FormLabel mr={1} mb={0} w="20%" fontSize="sm">
          currentValue ({sliderValue})
        </FormLabel>
        <Slider
          aria-label="slider-example"
          value={sliderValue ?? value}
          onChange={val => setSliderValue(val)}
          onChangeEnd={val => {if (val != value) {onChangeEndFunction(slider, val)}}}
        >
          <SliderTrack>
            <SliderFilledTrack />
          </SliderTrack>
          <SliderThumb />
        </Slider>
      </FormControl>
    </Box>
  );
}
```

Without the check for a changed value, this behavior causes some kind of update loop. Once it is triggered, it fills the console with `Maximum update depth exceeded` warnings (example below).

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/slider@1.1.2/dist/cjs/slider.js:40:48)
at div
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:35:23)
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/form-control@1.2.2/dist/cjs/form-control.js:97:48)
at div
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:35:23)
at SliderWithHandlers (https://multi-slider-example.stackblitz.io/~/src/SliderWithHandlers.jsx:25:13)
at div
at ColorModeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/color-mode@1.1.1/dist/cjs/color-mode-provider.js:51:21)
at ThemeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:93:21)
at ThemeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/system@1.4.0/dist/cjs/providers.js:22:34)
at ChakraProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/react@1.3.4/dist/cjs/chakra-provider.js:27:24)
at App (https://multi-slider-example.stackblitz.io/~/src/App.js:30:46)
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/slider@1.1.2/dist/cjs/slider.js:40:48)
at div
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:35:23)
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/form-control@1.2.2/dist/cjs/form-control.js:97:48)
at div
at eval (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:35:23)
at SliderWithHandlers (https://multi-slider-example.stackblitz.io/~/src/SliderWithHandlers.jsx:25:13)
at div
at ColorModeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/color-mode@1.1.1/dist/cjs/color-mode-provider.js:51:21)
at ThemeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@emotion/react@11.1.5/dist/emotion-element-cb6e9ca7.cjs.dev.js:93:21)
at ThemeProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/system@1.4.0/dist/cjs/providers.js:22:34)
at ChakraProvider (https://multi-slider-example.stackblitz.io/turbo_modules/@chakra-ui/react@1.3.4/dist/cjs/chakra-provider.js:27:24)
at App (https://multi-slider-example.stackblitz.io/~/src/App.js:30:46)
```
