### ISSUE TITLE
Storybook not working

### ISSUE THREAD

**Issue by jatin33** [chakra-ui/chakra-ui#3731]
# 🐛 Bug report

I am trying to contribute to Chakra-ui repo and When I ran ```yarn storybook``` in chakra-ui repo in my local machine, i faced errors.

## 💥 Steps to reproduce

1. Go to chakra-ui repo
2. Type ```yarn storybook```

## 💻 Link to reproduction

CodeSandbox reproduction: NA

## 🧐 Expected behavior

```yarn storybook``` should run storybook on localhost showing all components

## 🧭 Possible Solution

NA

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |         NA   |
| Browser          |       Chrome 89.0.4389.90     |
| Operating System |        Mac OS Catalina 10.15.6    |

## 📝 Additional information

Error stack
-------------
```
ERROR in ./.storybook/generated-refs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@chakra-ui/babel-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:315:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
    at resolve (internal/modules/cjs/helpers.js:80:19)
    at resolveStandardizedName (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePlugin (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPlugin (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at createDescriptor (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:415:26)
    at /Users/jatinpanjwani/opensource/chakra-ui/node_modules/@babel/core/lib/config/config-chain.js:374:7
    at Generator.next (<anonymous>)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js storybook-addon-performance/register ./node_modules/@storybook/addon-a11y/dist/register.js ./node_modules/@storybook/addon-toolbars/dist/register.js ./.storybook/generated-refs.js main[5]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.19 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.98 KiB {HtmlWebpackPlugin_0} [built]
WARN Force closed preview build
```
Video
-------
https://www.loom.com/share/862ab849ec3e4b6eaf809e52846f0de9

**Comment by segunadebayo** [comment]
Hi @jatin33, kindly run `yarn start` at the root of the project and this should resolve this error.

**Comment by jatin33** [comment]
working now, thanks 😊
