### ISSUE TITLE
Can't see storybooks on dev-ts branch

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#473]
**Describe the bug**

Running `yarn setup` throws the following error:

```sh
@chakra-ui/preset-base: (typescript) Error: src/components/NumberInput.ts:2:29 - error TS7016: Could not find a declaration file for module '@chakra-ui/system'. '/Users/aaronmcadam/learning/chakra-ui/node_modules/@chakra-ui/system/dist/index.js' implicitly has an 'any' type.
@chakra-ui/preset-base:   Try `npm install @types/chakra-ui__system` if it exists or add a new declaration (.d.ts) file containing `declare module '@chakra-ui/system';`
@chakra-ui/preset-base: 2 import { SystemProps } from "@chakra-ui/system"
@chakra-ui/preset-base:                               ~~~~~~~~~~~~~~~~~~~
@chakra-ui/preset-base: Error: src/components/NumberInput.ts:2:29 - error TS7016: Could not find a declaration file for module '@chakra-ui/system'. '/Users/aaronmcadam/learning/chakra-ui/node_modules/@chakra-ui/system/dist/index.js' implicitly has an 'any' type.
@chakra-ui/preset-base:   Try `npm install @types/chakra-ui__system` if it exists or add a new declaration (.d.ts) file containing `declare module '@chakra-ui/system';`
@chakra-ui/preset-base: 2 import { SystemProps } from "@chakra-ui/system"
@chakra-ui/preset-base:                               ~~~~~~~~~~~~~~~~~~~
@chakra-ui/preset-base:     at error (/Users/aaronmcadam/learning/chakra-ui/node_modules/rollup/dist/shared/node-entry.js:5400:30)
@chakra-ui/preset-base:     at throwPluginError (/Users/aaronmcadam/learning/chakra-ui/node_modules/rollup/dist/shared/node-entry.js:11874:12)
@chakra-ui/preset-base:     at Object.error (/Users/aaronmcadam/learning/chakra-ui/node_modules/rollup/dist/shared/node-entry.js:12908:24)
@chakra-ui/preset-base:     at Object.error (/Users/aaronmcadam/learning/chakra-ui/node_modules/rollup/dist/shared/node-entry.js:12077:38)
@chakra-ui/preset-base:     at RollupContext.error (/Users/aaronmcadam/learning/chakra-ui/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
@chakra-ui/preset-base:     at /Users/aaronmcadam/learning/chakra-ui/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24955:19
@chakra-ui/preset-base:     at arrayEach (/Users/aaronmcadam/learning/chakra-ui/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
@chakra-ui/preset-base:     at forEach (/Users/aaronmcadam/learning/chakra-ui/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
@chakra-ui/preset-base:     at printDiagnostics (/Users/aaronmcadam/learning/chakra-ui/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
```

**Expected Behavior**

I expect to be able to build the system so that I can look at the storybooks.

**Comment by tioluwani94** [comment]
Hi @aaronmcadam,

You can try running this on the command-line 

`yarn system build && yarn setup`

**Comment by aaronmcadam** [comment]
Ah thanks @tioluwani94, that fixed it! I don't know whether you'd want to include the `system build` in the `setup` line.

As an aside, I'm seeing this when running `yarn storybook`:

![Google Chrome 2020-03-05 at 09 43 37@2x](https://user-images.githubusercontent.com/37928/75968761-d26abc00-5ec5-11ea-8b4b-eb3e3a1959c8.png)

**Comment by segunadebayo** [comment]
@aaronmcadam, this has been fixed. You can now run `yarn build` and then `yarn storybook`.

If the problem still exists after running the command, I'll re-open this issue.

**Comment by aaronmcadam** [comment]
Hi @segunadebayo, it's nearly working. Now I see the following:

![Google Chrome 2020-03-09 at 12 22 48@2x](https://user-images.githubusercontent.com/37928/76212596-c140e880-6200-11ea-9d1c-0b52bbb1830f.png)

**Comment by segunadebayo** [comment]
Yes, this is due to the settings I added to the `.storybook/main.js`. I'm currently working on the drawer component that's why I constrained storybook to load only drawer stories.

To see all change the mention of `Drawer` to `**` to see all components.

**Comment by aaronmcadam** [comment]
Thanks @segunadebayo, we can keep this closed!
