### ISSUE TITLE
@chakra-ui/storybook-addon dependency issue

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#5336]
### Description

When trying to build Storybook with Chakra UI addon, I get a build error if `@chakra-ui/icons` is not explicitly added to the dependencies.

### Steps to reproduce

1. Install the official Storybook Addon for Chakra UI as mentioned in the [doc](https://www.npmjs.com/package/@chakra-ui/storybook-addon)

```shell
yarn add -D @chakra-ui/storybook-addon
```

2. In `.storybook/main.js`

```js
module.exports = {
  addons: ['@chakra-ui/storybook-addon'],
}
```

3. Start Storybook
4. See dependency error

### Chakra UI Version

1.7.4

**Comment by TylerAPfledderer** [comment]
Hello!

I too am receiving this error while trying to create a new React project.

```
$ yarn storybook
yarn run v1.22.5
$ start-storybook -p 6006 -s public
info @storybook/react v6.4.16
info
(node:11984) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/20 entries 100/218 dependencies 6/69 modules
info => Ignoring cached manager due to change in manager config
<i> [webpack-dev-middleware] wait until bundle finished
56% building 17/20 entries 6910/6917 dependencies 1700/1747 modulesassets by chunk 5.12 MiB (id hint: vendors)
  assets by status 4.74 MiB [big]
    asset vendors-node_modules_chakra-ui_storybook-addon_preset_register_dist_chakra-ui-storybook-addon-9be630.manager.bundle.js 4.37 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 115 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 66.8 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 3.28 KiB [emitted]
asset main.manager.bundle.js 2.44 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.3 KiB [emitted]
Entrypoint main [big] 4.39 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_chakra-ui_storybook-addon_preset_register_dist_chakra-ui-storybook-addon-9be630.manager.bundle.js 4.37 MiB main.manager.bundle.js 2.44 KiB
orphan modules 1.52 MiB [orphan] 335 modules
runtime modules 8.71 KiB 14 modules
javascript modules 4.55 MiB
  modules by path ./node_modules/ 4.55 MiB 915 modules
  ./.storybook/generated-refs.js 301 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.67.0) compiled successfully in 11489 ms
69% building finish ReactRefreshPluginassets by status 782 KiB [cached] 8 assets
assets by status 4.38 MiB [emitted]
  asset vendors-node_modules_chakra-ui_storybook-addon_preset_register_dist_chakra-ui-storybook-addon-9be630.manager.bundle.js 4.37 MiB [emitted] [big] (id hint: vendors)
  asset index.html 3.28 KiB [emitted]
Entrypoint main [big] 4.39 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_chakra-ui_storybook-addon_preset_register_dist_chakra-ui-storybook-addon-9be630.manager.bundle.js 4.37 MiB main.manager.bundle.js 2.44 KiB
cached modules 6.06 MiB (javascript) 8.71 KiB (runtime) [cached] 1265 modules
javascript modules 8.79 KiB
  ./node_modules/@storybook/addon-controls/dist/esm/register.js + 3 modules 6.44 KiB [code generated]
  ./.storybook/generated-refs.js 301 bytes [built]
  ./node_modules/@storybook/components/dist/esm/index.js 2.05 KiB [code generated]
manager (webpack 5.67.0) compiled successfully in 487 ms
99% done plugins webpack-hot-middlewarewebpack built preview 9b64583bae290ae2e3f1 in 19533ms
ModuleNotFoundError: Module not found: Error: Can't resolve '@chakra-ui/icons' in 'C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\decorators\dist' 
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\Compilation.js:2013:28
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:795:13
    at eval (eval at create (C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:431:22
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:124:11
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:667:25
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:852:8
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:972:5
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\neo-async\async.js:6883:13
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\webpack\lib\NormalModuleFactory.js:955:45
    at finishWithoutResolve (C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\enhanced-resolve\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve '@chakra-ui/icons' in 'C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\decorators\dist'
  Parsed request is a module
  using description file: C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\decorators\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\decorators\dist\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\decorators\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\preset\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\storybook-addon\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules
        single file module
          using description file: C:\Users\tyler\Documents\Sites\lesson-scheduler\package.json (relative path: ./node_modules/@chakra-ui/icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons.jsx doesn't exist
        C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\@chakra-ui\icons doesn't exist
      C:\Users\tyler\Documents\Sites\node_modules doesn't exist or is not a directory
      C:\Users\tyler\Documents\node_modules doesn't exist or is not a directory
      C:\Users\tyler\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules
        single file module
          using description file: C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\package.json (relative path: ./node_modules/@chakra-ui/icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons.jsx doesn't exist
        C:\Users\tyler\Documents\Sites\lesson-scheduler\node_modules\react-scripts\node_modules\@chakra-ui\icons doesn't exist
```

Chakra UI version: `^1.8.1`

.storybook/main.js
```javascript
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    '@storybook/addon-a11y',
    '@chakra-ui/storybook-addon',
  ],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
  // unpins Storybook's dependence on Emotion 10 so that build can compile successfully
  features: { emotionAlias: false },
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // https://github.com/polkadot-js/extension/issues/621#issuecomment-759341776
    // framer-motion uses the .mjs notation and we need to include it so that webpack will
    // transpile it for us correctly (enables using a CJS module inside an ESM).
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    });
    // Return the altered config
    return config;
  },
};
```
