### ISSUE TITLE
Search on Chakra site is broken

### ISSUE THREAD

**Issue by sgehrman** [chakra-ui/chakra-ui#5648]
### Description

search broken

### Link to Reproduction

https://what.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.8

### Browser

chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Uncaught TypeError: Cannot read properties of undefined (reading 'url')
    at omni-search.tsx:187:39
    at Object.$e (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at xr (react-dom.production.min.js:100:68)
    at Cr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Fe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57

**Comment by m4x3d** [comment]
Hey @sgehrman, thanks for opening that issue!

Can you please specify it a bit more? Maybe with an example what do you searched for exactly?
And I guess you mean the search on the top of https://chakra-ui.com/? It works for me as expected, can not reproduce it by myself, but if there is a bug than I want to fix it immediately.

**Comment by noobinthisgame** [comment]
@TimKolberger @nikolovlazar This is a docs issue, could you move it over to the docs repo ?
