### ISSUE TITLE
Yarn install fails after fresh clone

### ISSUE THREAD

**Issue by jonbri** [chakra-ui/chakra-ui#5813]
### Description

When I try to install dependencies after a fresh project clone it fails

### Link to Reproduction

This occurs in the terminal

### Steps to reproduce

Fresh clone:
```sh
git clone git@github.com:chakra-ui/chakra-ui.git
cd chakra-ui
```

Install dependencies:
```
yarn
```

Error shown in terminal:
```sh
[4/5] Building fresh packages...
[1/9] ⢀ core-js
[6/9] ⢀ gatsby-telemetry
[3/9] ⢀ iltorb
[4/9] ⢀ ejs
error /home/j/chakra-ui/node_modules/iltorb: Command failed.
Exit code: 1
Command: node ./scripts/install.js || node-gyp rebuild
Arguments:
Directory: /home/j/chakra-ui/node_modules/iltorb
Output:
info looking for cached prebuild @ /home/j/.npm/_prebuilds/c57c4d-iltorb-v2.4.5-node-v83-linux-x64.tar.gz
http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gzhttp 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
WARN install No prebuilt binaries found (target=14.19.1 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.19.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/j/chakra-ui/node_modules/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/j/.cache/node-gyp/14.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/j/.cache/node-gyp/14.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/j/.cache/node-gyp/14.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/j/chakra-ui/node_modules/iltorb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: cc: Command not found
make: *** [iltorb.target.mk:150: Release/obj.target/iltorb/brotli/c/common/dictionary.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/j/chakra-ui/node_modules/iltorb
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

### Chakra UI Version

Latest from repo's `main` branch. I'm on commit 3c59f6d7623

### Browser

in terminal

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I'm using WSL2
Node v14.19.1
NPM 6.14.16
Yarn 1.19.1

**Comment by jonbri** [comment]
Was able to get past this after installing `make` and `g++`
