### ISSUE TITLE
Tabs gives key error

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [chakra-ui/chakra-ui#6564]
### Description

The tabs component gives the `each child in a list should have a unique key prop`

### Link to Reproduction

none

### Steps to reproduce

following this structure
```
<Tabs orientation="vertical" w="full" px={5} isLazy index={0}>
          <TabList>
            <Tab>
              <Text textAlign="start" fontWeight="bold" textTransform="uppercase">
                Project Deliverables
              </Text>
            </Tab>

            <Tab>
              <Text textAlign="start" fontWeight="bold" textTransform="uppercase">
                Project Timeline
              </Text>
            </Tab>

            <Tab>
              <Text textAlign="start" fontWeight="bold" textTransform="uppercase">
                Project Scope
              </Text>
            </Tab>
          </TabList>

          <TabPanels pl={10} key={0}>
            <TabPanel p={0} key={0}>
              <VStack w="full" align="start">
                <Heading fontSize="3xl" lineHeight="10" fontWeight="extrabold">
                  Project Deliverables
                </Heading>

                <Text dangerouslySetInnerHTML={{ __html: data.deliverables }} />
              </VStack>
            </TabPanel>

            <TabPanel p={0} key={1}>
              <VStack w="full" align="start">
                <Heading fontSize="3xl" lineHeight="10" fontWeight="extrabold">
                  Project Timeline
                </Heading>

                <Text dangerouslySetInnerHTML={{ __html: data.timeline }} />
              </VStack>
            </TabPanel>

            <TabPanel p={0} key={2}>
              <VStack w="full" align="start">
                <Heading fontSize="3xl" lineHeight="10" fontWeight="extrabold">
                  Project Scope
                </Heading>

                <Text dangerouslySetInnerHTML={{ __html: data.scope }} />
              </VStack>
            </TabPanel>
          </TabPanels>
        </Tabs>
```

this error appears:
`
next-dev.js?481c:24 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at TabPanels2 (webpack-internal:///./node_modules/.pnpm/@chakra-ui+tabs@2.1.0_uq4pd65cbukopacjandqfokfmm/node_modules/@chakra-ui/tabs/dist/index.esm.js:376:23)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Tabs2 (webpack-internal:///./node_modules/.pnpm/@chakra-ui+tabs@2.1.0_uq4pd65cbukopacjandqfokfmm/node_modules/@chakra-ui/tabs/dist/index.esm.js:304:88)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at eval (webpack-internal:///./node_modules/.pnpm/@chakra-ui+layout@2.1.6_uq4pd65cbukopacjandqfokfmm/node_modules/@chakra-ui/layout/dist/index.esm.js:714:5)
    at VStack
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at eval (webpack-internal:///./node_modules/.pnpm/@chakra-ui+layout@2.1.6_uq4pd65cbukopacjandqfokfmm/node_modules/@chakra-ui/layout/dist/index.esm.js:714:5)
    at VStack
    at ProposalByIdPage (webpack-internal:///./pages/intakes/[id]/[proposalId]/index.tsx:23:69)
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Container2 (webpack-internal:///./node_modules/.pnpm/@chakra-ui+layout@2.1.6_uq4pd65cbukopacjandqfokfmm/node_modules/@chakra-ui/layout/dist/index.esm.js:206:83)
    at main
    at eval (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at MainLayout (webpack-internal:///./ui/Layout/MainLayout.tsx:26:26)
    at EnvironmentProvider (webpack-internal:///./node_modules/.pnpm/@chakra-ui+react-env@2.0.9_react@18.1.0/node_modules/@chakra-ui/react-env/dist/index.esm.js:121:11)
    at ColorModeProvider (webpack-internal:///./node_modules/.pnpm/@chakra-ui+color-mode@2.1.7_react@18.1.0/node_modules/@chakra-ui/color-mode/dist/index.esm.js:158:5)
    at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@emotion+react@11.10.0_oxv4y2q7piv6yxkblr7zey5zvm/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@chakra-ui+system@2.2.7_oj5smyx4pkioqvs6eohmxginfy/node_modules/@chakra-ui/system/dist/index.esm.js:112:11)
    at ChakraProvider (webpack-internal:///./node_modules/.pnpm/@chakra-ui+provider@2.0.14_w77int5dzy4ge325wncun3akkm/node_modules/@chakra-ui/provider/dist/index.esm.js:21:5)
    at ChakraProvider (webpack-internal:///./node_modules/.pnpm/@chakra-ui+react@2.2.9_slovfir5r7yzzrv5etqc6ievgi/node_modules/@chakra-ui/react/dist/index.esm.js:245:3)
    at SWRConfig$1 (webpack-internal:///./node_modules/.pnpm/swr@1.3.0_react@18.1.0/node_modules/swr/dist/index.mjs:504:23)
    at MyApp (webpack-internal:///./pages/_app.tsx:43:28)
    at ErrorBoundary (webpack-internal:///./node_modules/.pnpm/next@12.2.0_mihsxpuqvgf3kzmp2yw7mj4cuy/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/.pnpm/next@12.2.0_mihsxpuqvgf3kzmp2yw7mj4cuy/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23199)
    at Container (webpack-internal:///./node_modules/.pnpm/next@12.2.0_mihsxpuqvgf3kzmp2yw7mj4cuy/node_modules/next/dist/client/index.js:149:9)
    at AppContainer (webpack-internal:///./node_modules/.pnpm/next@12.2.0_mihsxpuqvgf3kzmp2yw7mj4cuy/node_modules/next/dist/client/index.js:651:26)
    at Root (webpack-internal:///./node_modules/.pnpm/next@12.2.0_mihsxpuqvgf3kzmp2yw7mj4cuy/node_modules/next/dist/client/index.js:773:27)
window.console.error @ next-dev.js?481c:24
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react-dom.development.js?33f1:86
error @ react-dom.development.js?33f1:60
warnForMissingKey @ react-dom.development.js?33f1:14666
warnOnInvalidKey @ react-dom.development.js?33f1:15145
reconcileChildrenArray @ react-dom.development.js?33f1:15200
reconcileChildFibers @ react-dom.development.js?33f1:15691
reconcileChildren @ react-dom.development.js?33f1:19964
updateHostComponent$1 @ react-dom.development.js?33f1:20733
beginWork @ react-dom.development.js?33f1:22447
beginWork$1 @ react-dom.development.js?33f1:27381
performUnitOfWork @ react-dom.development.js?33f1:26513
workLoopSync @ react-dom.development.js?33f1:26422
renderRootSync @ react-dom.development.js?33f1:26390
performConcurrentWorkOnRoot @ react-dom.development.js?33f1:25694
workLoop @ scheduler.development.js?57cf:266
flushWork @ scheduler.development.js?57cf:239
performWorkUntilDeadline @ scheduler.development.js?57cf:533
`

### Chakra UI Version

2.2.1

### Browser

arc (chromium based)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

this should obviously not happen

**Comment by coopbri** [comment]
I am receiving this error as well with default (automated/Chakra-defined) keys. Interestingly, the keys seem fine and distinct in the render tree:

![tab-keys](https://user-images.githubusercontent.com/20056195/186828618-1131cb2e-5b19-47e4-874e-fca1761ed12f.png)

Will report back after digging into this some more!

**Comment by segunadebayo** [comment]
Good catch.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
