### ISSUE TITLE
Unexpected token when installing to a Next.js project

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#6588]
### Description

When I install chakra UI to a fresh Next js project, I expect it to *not* throw an error:
```
/Users/tom/Code/playground/chakra-bug/node_modules/@chakra-ui/accordion/dist/index.cjs.js:136
        return defaultIndex ?? [];
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/tom/Code/playground/chakra-bug/node_modules/@chakra-ui/react/dist/index.cjs.js:41:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

### Link to Reproduction

https://github.com/tomdohnal/next-js-chakra-ui-bug

### Steps to reproduce

1) Clone the repo: https://github.com/tomdohnal/next-js-chakra-ui-bug
2) Install the deps (`yarn`)
3) Run the project (`yarn dev`)
4) See the error

### Chakra UI Version

2.2.9

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tomdohnal** [comment]
OK so the problem was i was using an old Node.js version (12) instead of 16. That said, I think the `@chakra-ui/react` package should specify a minimum Node.js version so that the install fails if the Node.js version criteria aren't met

**Comment by gmssameer** [comment]
how did you resolve the issue, should the "Next" version be changed ?

**Comment by tomdohnal** [comment]
no it wasn't related to Next.js at all in the end, it was just that i was using an old (and unsupported) Node.js version
