### ISSUE TITLE
localStorage issues

### ISSUE THREAD

**Issue by giovanni-bozzano** [chakra-ui/chakra-ui#739]
I am working on a desktop webapp that relies on Chakra for the UI rendering.
I am having issues using `ColorModeProvider`. Specifically using `<DarkMode>`.
It appears that on macOS (Safari WKWebView) the page is not able to access `localStorage` and it just crashes.

It would be nice to have a switch option to use/not use the `localStorage` feature provided by the use-dark-mode library and just let my application handle the user preference.

**Comment by with-heart** [comment]
I believe this should no longer be an issue once 1.0 is released, but I'll let @segunadebayo speak to that.

**Comment by Aidurber** [comment]
I think the quickest way would be to pass a storage interface to the `ColorModeProvider` component. That's is how [redux-persist](https://github.com/rt2zz/redux-persist#v6-upgrade) handles it. 

However, since the `ColorModeProvider` value is `light | dark`. This requires a breaking change unless the provider is wrapped and takes `value` and `storage` as props. So you're looking at a v1 regardless 😬 

**Storage prop**
```typescript
interface IStorage{
 setItem(key:string, value:string);
 getItem(key:string):string;
 removeItem(key:string):string
// etc.
}
```

You then get into the problem of [creating adapters](https://github.com/rt2zz/redux-persist#storage-engines). 

One possible way to do this without a breaking change would be to add an optional config call.

```jsx
function App(){
  React.useEffect(() => {
    Chakra.configure({
      storage: localStorage
    })
  }, [])
 return //
}
```
[This approach is used by Atomic Layout](https://redd.gitbook.io/atomic-layout/api/layout/configure)

Then the ColorModeProvider takes that value (defaulting to localStorage for backwards compatibility). Or even as part of the theme object, but I'm not a fan of that approach since it's mixing concerns.

**Comment by dedo1911** [comment]
I just got around the issue with a solution like this:

```jsx
import { ColorModeContext } from '@chakra-ui/core'

const DarkMode = props => {
  const darkMode = {
    colorMode: 'dark',
    toggleColorMode: _ => {}
  }
  return <ColorModeContext.Provider value={darkMode}>
    {props.children}
  </ColorModeContext.Provider>
}
```

What I did is basically defining my own `DarkMode` color provider that doesn't use anything but a `colorMode` property.
You should implement your custom `toggleColorMode` or set `colorMode` with your rules.

**Comment by Aidurber** [comment]
@dedo1911 Good thinking! Much simpler than anything I suggested 😁

**Comment by with-heart** [comment]
Color mode now works correctly with `localStorage` in 1.0! https://next.chakra-ui.com/docs/color-mode

**Comment by burhanuday** [comment]
> I just got around the issue with a solution like this:
> 
> ```js-jsx
> import React from 'react'
> import { CSSReset, ColorModeContext } from '@chakra-ui/core'
> 
> const ColorModeProvider = props => {
>   const colorMode = {
>     colorMode: props.value || 'light',
>     toggleColorMode: _ => {}
>   }
> 
>   return <ColorModeContext.Provider value={colorMode}>
>     <CSSReset />
>     {props.children}
>   </ColorModeContext.Provider>
> }
> 
> export default ColorModeProvider
> ```
> 
> What I did is basically defining my own `ColorModeProvider` that doesn't use anything but a `colorMode` property.
> You should implement your custom `toggleColorMode` or set `colorMode` with your rules.

@dedo1911 @with-heart  This does not seem to work for me on Chakra 1.0.4
I am rendering a page inside an iframe and i get the following error
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

at Object.get (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/storage-manager.js:17:29)
    at eval (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:73:213)
    at invokePassiveEffectCreate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23482:20)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23569:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:646:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23442:14)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23319:11)
    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:590:34)
    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:545:16)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:157:27)
The above error occurred in the <ColorModeProvider> component:

    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:46:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:78:71)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/react/dist/esm/chakra-provider.js:21:5)
    at MyApp (webpack-internal:///./pages/_app.js:48:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:150:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:639:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:764:24)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```
