### ISSUE TITLE
CLI fails to generate types when `"jsx": "react-jsx"` transform is used in tsconfig

### ISSUE THREAD

**Issue by psychedelicious** [chakra-ui/chakra-ui#7394]
### Description

CLI fails to generate types when `"jsx": "react-jsx"` transform is used in tsconfig. Errors:

```
$ chakra-cli tokens src/theme/theme.ts

 Chakra UI CLI  v2.3.0 by Chakra UI
Generate theme typings for autocomplete


✖ An error occurred
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.

TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.

    at createTSError (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/ts-node/src/index.ts:874:36)
    at create (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/ts-node/src/index.ts:624:10)
    at Object.register (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/ts-node/src/index.ts:591:15)
    at readTheme (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js:49:12)
    at run (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js:97:23)
    at Object.<anonymous> (/home/bat/Documents/Code/InvokeAI/invokeai/frontend/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js:118:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "baseUrl": "src",
    "jsx": "react-jsx"
  },
  "include": ["src", "index.d.ts"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

This patch fixes it and the CLI successfully generates types:
```
diff --git a/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js b/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js
index 937cf0d..7dcc0c0 100644
--- a/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js
+++ b/node_modules/@chakra-ui/cli/dist/scripts/read-theme-file.worker.js
@@ -50,7 +50,8 @@ async function readTheme(themeFilePath) {
       project: tsConfig.configFileAbsolutePath,
       compilerOptions: {
         module: "CommonJS",
-        esModuleInterop: true
+        esModuleInterop: true,
+        jsx: 'react'
       },
       transpileOnly: true,
       swc: true
```

But I have a feeling something else is wonky with my setup. Is this a bug or a problem on my end?

Note: I'm not sure how to provide a reproduction link given the issue is with the nodejs CLI.

### Link to Reproduction

n/a

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by psychedelicious** [comment]
This is resolved in `@chakra-ui/cli` version 2.4.1.
