### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by R3flector** [chakra-ui/chakra-ui#7658]
### Description

GET https://registry.npmjs.org/@chakra-ui%2Fcontrol-box: Not Found - 404

This error happened while installing the dependencies of @chakra-ui/react@2.6.1

@chakra-ui/control-box is not in the npm registry, or you have no permission to fetch it.

### Link to Reproduction

https://www.npmjs.com/login?next=%2Fpackage%2F%40chakra-ui%2Fcontrol-box

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by joshmertens** [comment]
I'm getting a few of them

```
error Couldn't find package "@chakra-ui/avatar@2.2.5" required by "@chakra-ui/react@2.5.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@chakra-ui/control-box@2.0.13" required by "@chakra-ui/react@2.5.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@chakra-ui/styled-system@2.6.1" required by "@chakra-ui/react@2.5.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@chakra-ui/styled-system@2.6.1" required by "@chakra-ui/system@2.5.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@chakra-ui/styled-system@2.6.1" required by "@chakra-ui/theme-utils@2.0.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@chakra-ui/styled-system@2.6.1" required by "@chakra-ui/toast@6.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by R3flector** [comment]
![image](https://github.com/chakra-ui/chakra-ui/assets/58531356/cdb6f5ab-fe62-48bf-85e7-17a8816c6ee8)

**Comment by jamezrin** [comment]
I think it's an issue on npm's side, I am getting Service Unavailable errors and every package I search on the website requires me to login.

**Comment by VivekAlhat** [comment]
I am also getting the following error during fresh chakra UI installation.

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@chakra-ui%2favatar - Not found
npm ERR! 404
npm ERR! 404  '@chakra-ui/avatar@2.2.10' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

Looks like an issue on NPM side

**Comment by devnm21** [comment]
Been getting the same error during build

![image](https://github.com/chakra-ui/chakra-ui/assets/93040511/2f13a7ef-1d98-4780-a42e-158205567770)

**Comment by Vatar** [comment]
Yup it's definetely an issue on NPM side, the npmjs download links for those packages are down, we have to wait for NPM to fix it

**Comment by vileen** [comment]
Seems to be working now
