### ISSUE TITLE
Chakra v3 Accordion Next.js errors

### ISSUE THREAD

**Issue by jdddog** [chakra-ui/chakra-ui#8509]
### Description

The Chakra UI V3 `Accordion` has a couple of errors in Next.js, some of which occur when the edge runtime is used.

Default example:
```typescript
const DemoAccordion = () => {
  const items = [
    { value: "a", title: "First Item", text: "Some value 1..." },
    { value: "b", title: "Second Item", text: "Some value 2..." },
    { value: "c", title: "Third Item", text: "Some value 3..." },
  ]
  
  return (
    <Accordion.Root minW="300px" defaultValue={["b"]}>
      {items.map((item, index) => (
        <Accordion.Item key={index} value={item.value}>
          <h2>
            <Accordion.ItemTrigger>
              <Box flex="1" textAlign="start">
                {item.title}
              </Box>
              <Accordion.ItemIndicator>
                <Icon as={HiChevronDown} />
              </Accordion.ItemIndicator>
            </Accordion.ItemTrigger>
          </h2>
          <Accordion.ItemContent>
            <Accordion.ItemBody>{item.text}</Accordion.ItemBody>
          </Accordion.ItemContent>
        </Accordion.Item>
      ))}
    </Accordion.Root>
  )
}
```

Error 1: When the component the `Accordion` is used within isn't wrapped with "use client":
```typescript
 ⨯ TypeError: (0 , _styled_system_create_style_context_mjs__WEBPACK_IMPORTED_MODULE_0__.createStyleContext) is not a function
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
    at eval (./app/a/page.tsx:7:74)
    at (rsc)/./app/a/page.tsx (/path/to/next-app/.next/server/app/a/page.js:5102:1)
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
digest: "778862165"
 ⨯ TypeError: (0 , _styled_system_create_style_context_mjs__WEBPACK_IMPORTED_MODULE_0__.createStyleContext) is not a function
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
    at eval (./app/a/page.tsx:7:74)
    at (rsc)/./app/a/page.tsx (/path/to/next-app/.next/server/app/a/page.js:5102:1)
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
digest: "778862165"
 ⨯ TypeError: (0 , _styled_system_create_style_context_mjs__WEBPACK_IMPORTED_MODULE_0__.createStyleContext) is not a function
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
    at eval (./app/a/page.tsx:7:74)
    at (rsc)/./app/a/page.tsx (/path/to/next-app/.next/server/app/a/page.js:5102:1)
    at __webpack_require__ (/path/to/next-app/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/path/to/next-app/.next/server/edge-runtime-webpack.js:288:21)
digest: "3021769049"
 [Error: (0 , _styled_system_create_style_context_mjs__WEBPACK_IMPORTED_MODULE_0__.createStyleContext) is not a function] {
  digest: '3021769049'
}
 ⨯  [Error: (0 , _styled_system_create_style_context_mjs__WEBPACK_IMPORTED_MODULE_0__.createStyleContext) is not a function] {
  digest: '3021769049'
}
 ⨯ [TypeError: Cannot read properties of null (reading 'default')]
```

Error 2: On a server render, when the `Accordion` is used in a component wrapped in "use client", and the edge runtime is used:
```typescript
 ⨯ Internal error: TypeError: Cannot read properties of undefined (reading 'length')
    at coarseValue (./node_modules/@ark-ui/react/node_modules/@zag-js/accordion/dist/index.mjs:17:7109)
    at Machine.eval [as executeActions] (./node_modules/@zag-js/core/dist/index.mjs:17:13126)
    at Machine.eval [as _created] (./node_modules/@zag-js/core/dist/index.mjs:17:6233)
    at eval (./node_modules/@zag-js/react/dist/index.mjs:168:18)
    at useConstant (./node_modules/@zag-js/react/dist/index.mjs:157:12)
    at useService (./node_modules/@zag-js/react/dist/index.mjs:165:21)
    at useMachine (./node_modules/@zag-js/react/dist/index.mjs:180:21)
    at useAccordion (./node_modules/@ark-ui/react/dist/components/accordion/use-accordion.js:33:84)
    at eval (./node_modules/@ark-ui/react/dist/components/accordion/accordion-root.js:35:86)
    at renderWithHooks (./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9675:16)
```

A workaround for the first error is to put the Accordion into a separate component and wrap it with "use client" and the workaround for the second error is to remove `defaultValue` and explicitly manage the Accordion value with `useState`, however, I suspect that Accordion needs to be wrapped with "use client" in Chakra and the second error might be an error in the Zag accordion component?

```typescript
// Added "use client";
"use client";

import {Accordion, Box, Icon} from "@chakra-ui/react"
import {ChevronDown} from "lucide-react"
import React from 'react'

const items = [
    {value: "a", title: "First Item", text: "Some value 1..."},
    {value: "b", title: "Second Item", text: "Some value 2..."},
    {value: "c", title: "Third Item", text: "Some value 3..."},
]

export const AccordionUseClientUseState = () => {
    // Removed defaultValue={["b"]} and explicitly manage value state
    const [value, setValue] = React.useState<string[]>(["b"]);
    return (
        <Accordion.Root minW="300px" value={value} onValueChange={(val) => setValue(val)}>
            {items.map((item, index) => (
                <Accordion.Item key={index} value={item.value}>
                    <h2>
                        <Accordion.ItemTrigger>
                            <Box flex="1" textAlign="start">
                                {item.title}
                            </Box>
                            <Accordion.ItemIndicator>
                                <Icon as={ChevronDown}/>
                            </Accordion.ItemIndicator>
                        </Accordion.ItemTrigger>
                    </h2>
                    <Accordion.ItemContent>
                        <Accordion.ItemBody>{item.text}</Accordion.ItemBody>
                    </Accordion.ItemContent>
                </Accordion.Item>
            ))}
        </Accordion.Root>
    )
}
```

See Github repo and CodeSandbox for reproduction: https://github.com/jdddog/chakra-v3-accordion-errors

### Link to Reproduction

https://codesandbox.io/p/github/jdddog/chakra-v3-accordion-errors/main?import=true

### Steps to reproduce

Make sure that you open dev (server) console so that you can see server errors:

![image](https://github.com/chakra-ui/chakra-ui/assets/5715104/35b69d29-446f-4d70-857a-bd46909518af)

Then click on the different links to see the errors and a functional accordion:

![image](https://github.com/chakra-ui/chakra-ui/assets/5715104/624abcb4-925b-47d3-8edc-6c3288eeb55c)

If you don't see the errors for some reason then make sure that the page was rendered with server navigation (not client side navigation).

### Chakra UI Version

3.0.0-next.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Noted. Thanks

**Comment by jdddog** [comment]
Thanks @segunadebayo!
