### ISSUE TITLE
AvatarGroup - React does not recognize the showBorder prop.

### ISSUE THREAD

**Issue by dkrefta** [chakra-ui/chakra-ui#8805]
### Description

I encountered an issue after I started using AvatarGroup. It mentions that the showBorder prop is not valid for the DOM. Is there a way to remove this annoying warning?
next-dev.js:28 Warning: React does not recognize the `showBorder` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showborder` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at AvatarGroup2 (webpack-internal:///./node_modules/@chakra-ui/avatar/dist/chunk-A4TTV745.mjs:34:90)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at AvatarGroup (webpack-internal:///./components/communication/AvatarGroup/index.tsx:24:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at ProjectPreview (webpack-internal:///./components/templates/Posts/ProjectPreview/index.tsx:24:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at ProjectPostData (webpack-internal:///./components/templates/Posts/ProjectPostData/index.tsx:16:25)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at PostContent (webpack-internal:///./containers/Posts/PostContent/index.tsx:39:22)
    at div
    at div
    at InfiniteScroll (webpack-internal:///./node_modules/react-infinite-scroll-component/dist/index.es.js:199:28)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at Container2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-5MKCW436.mjs:16:83)
    at GlobalContainer (webpack-internal:///./components/containment/GlobalContainer/index.tsx:15:26)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:50:102)
    at Flex2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-KRPLQIP4.mjs:13:11)
    at DashboardLayout (webpack-internal:///./containers/Layout/DashboardLayout/index.tsx:43:27)
    at FollowersFeedPageContent (webpack-internal:///./containers/FollowersFeedPageContent/index.tsx:37:22)
    at FollowingFeed (webpack-internal:///./pages/channel/following/index.tsx:14:22)
    at GlobalWrapper (webpack-internal:///./containers/Layout/GlobalWrapper/index.tsx:35:27)
    at t.LitteraProvider (webpack-internal:///./node_modules/@assembless/react-littera/dist/index.js:1:1213)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/chunk-VMD3UMGK.mjs:34:11)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/chunk-AMBGAKG2.mjs:29:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:123:50)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-MFVQSVQB.mjs:28:11)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/chunk-3DDHO3UN.mjs:20:5)
    at ChakraProvider2 (webpack-internal:///./node_modules/@chakra-ui/react/dist/chunk-QAITB7GG.mjs:19:5)
    at FeatsChakraProvider (webpack-internal:///./config/providers/FeatsChakraProvider.tsx:26:26)
    at MixpanelProvider (webpack-internal:///./node_modules/react-mixpanel/lib/MixpanelContext.js:41:3)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:13:3)
    at App (webpack-internal:///./pages/_app.tsx:91:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:216:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:407:27)

### Link to Reproduction

codesandbox.io 

### Steps to reproduce

1. Import the AvatarGroup
2. Check the console log

### Chakra UI Version

2.8.2

### Browser

 128.0.6613.114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.

**Comment by dkrefta** [comment]
@segunadebayo  it's the same issue from here:
https://github.com/chakra-ui/chakra-ui/issues/6758
