### ISSUE TITLE
CheckboxGroup breaks when wrapped by FormControl

### ISSUE THREAD

**Issue by benshanahan1** [chakra-ui/chakra-ui#8938]
### Description

On upgrading, from 2.8.2 -> 2.10.2, a checkbox group stopped performing as expected.

Behavior (from the codesandbox link):
![2024-10-15 18 55 40](https://github.com/user-attachments/assets/825e8d8e-346b-4bad-a255-f9b7fd7ab76d)

### Link to Reproduction

https://codesandbox.io/p/sandbox/lm9dns

### Steps to reproduce

Here is a codesandbox that demonstrates the bug. If you remove the FormControl wrapping component, things work correctly.
https://codesandbox.io/p/sandbox/lm9dns

With FormControl:
![2024-10-15 18 55 40](https://github.com/user-attachments/assets/ec94acc1-dcd6-46f8-97e9-e112fbe5ad43)

Without FormControl around CheckboxGroup:
![2024-10-15 18 55 56](https://github.com/user-attachments/assets/5696d0a6-704d-4493-9037-3f9862ff4f7f)

### Chakra UI Version

2.10.2

### Browser

Google Chrome 129.0.6668.100

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TempVoice** [comment]
I can confirm this issue. Beside the performance issues which should be addressed soon another reason why we rolled back to 2.8.2

**Comment by segunadebayo** [comment]
Sorry about that.  I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by benshanahan1** [comment]
Awesome, thank you!

**Comment by benshanahan1** [comment]
@segunadebayo thanks for making this update. For some reason it appears that 2.10.3 breaks tests using a `render()` function, imported via `import { fireEvent, render } from '@testing-library/react'`.

```
FAIL src/__tests__/OperationForm.test.tsx
  ● Console

    console.error
      Error: Uncaught [TypeError: undefined is not a function]
          at reportException (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at innerInvokeEventListeners (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
          at invokeEventListeners (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
          at HTMLUnknownElementImpl._dispatch (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
          at HTMLUnknownElementImpl.dispatchEvent (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
          at HTMLUnknownElement.dispatchEvent (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
          at Object.invokeGuardedCallbackDev (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
          at invokeGuardedCallback (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
          at beginWork$1 (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:27490:7)
          at performUnitOfWork (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26599:[12](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:13))
          at workLoopSync (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26505:5)
          at renderRootSync (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26473:7)
          at performConcurrentWorkOnRoot (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:25777:74)
          at flushActQueue (/home/runner/work/factory-web/factory-web/node_modules/react/cjs/react.development.js:2667:24)
          at act (/home/runner/work/factory-web/factory-web/node_modules/react/cjs/react.development.js:2582:11)
          at /home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/act-compat.js:47:25
          at renderRoot (/home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/pure.js:180:26)
          at render (/home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/pure.js:271:10)
          at Object.<anonymous> (/home/runner/work/factory-web/factory-web/src/__tests__/OperationForm.test.tsx:[13](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:14):11)
          at Promise.then.completed (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/utils.js:298:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/utils.js:231:10)
          at _callCircusTest (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:316:40)
          at async _runTest (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:252:3)
          at async _runTestsForDescribeBlock (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:126:9)
          at async _runTestsForDescribeBlock (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:121:9)
          at async run (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:71:3)
          at async runAndTransformResultsToJestFormat (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
          at async jestAdapter (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
          at async runTestInternal (/home/runner/work/factory-web/factory-web/node_modules/jest-runner/build/runTest.js:367:16)
          at async runTest (/home/runner/work/factory-web/factory-web/node_modules/jest-runner/build/runTest.js:444:34) {
        detail: TypeError: undefined is not a function
            at Array.filter (<anonymous>)
            at fn (/home/runner/work/factory-web/factory-web/node_modules/@chakra-ui/utils/dist/cjs/split-props.cjs:17:62)
            at Array.map (<anonymous>)
            at Object.splitProps (/home/runner/work/factory-web/factory-web/node_modules/@chakra-ui/utils/dist/cjs/split-props.cjs:18:15)
            at /home/runner/work/factory-web/factory-web/node_modules/@chakra-ui/react/dist/cjs/system/system.cjs:[14](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:15):30
            at handleInterpolation (/home/runner/work/factory-web/factory-web/node_modules/@emotion/styled/node_modules/@emotion/serialize/dist/emotion-serialize.cjs.js:120:24)
            at Object.serializeStyles (/home/runner/work/factory-web/factory-web/node_modules/@emotion/styled/node_modules/@emotion/serialize/dist/emotion-serialize.cjs.js:212:[15](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:16))
            at /home/runner/work/factory-web/factory-web/node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.cjs.js:211:34
            at /home/runner/work/factory-web/factory-web/node_modules/@emotion/react/dist/emotion-element-832b737b.browser.cjs.js:72:12
            at renderWithHooks (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:15486:18)
            at updateForwardRef (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:19245:20)
            at beginWork (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:2[16](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:17)75:16)
            at HTMLUnknownElement.callCallback (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:4164:14)
            at HTMLUnknownElement.callTheUserObjectsOperation (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
            at innerInvokeEventListeners (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
            at invokeEventListeners (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
            at HTMLUnknownElementImpl._dispatch (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
            at HTMLUnknownElementImpl.dispatchEvent (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:[17](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:18))
            at HTMLUnknownElement.dispatchEvent (/home/runner/work/factory-web/factory-web/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
            at Object.invokeGuardedCallbackDev (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
            at invokeGuardedCallback (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
            at beginWork$1 (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:27490:7)
            at performUnitOfWork (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26599:12)
            at workLoopSync (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26505:5)
            at renderRootSync (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:26473:7)
            at performConcurrentWorkOnRoot (/home/runner/work/factory-web/factory-web/node_modules/react-dom/cjs/react-dom.development.js:25777:74)
            at flushActQueue (/home/runner/work/factory-web/factory-web/node_modules/react/cjs/react.development.js:2667:24)
            at act (/home/runner/work/factory-web/factory-web/node_modules/react/cjs/react.development.js:2582:11)
            at /home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/act-compat.js:47:25
            at renderRoot (/home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/pure.js:[18](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:19)0:26)
            at render (/home/runner/work/factory-web/factory-web/node_modules/@testing-library/react/dist/pure.js:271:10)
            at Object.<anonymous> (/home/runner/work/factory-web/factory-web/src/__tests__/OperationForm.test.tsx:13:11)
            at Promise.then.completed (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/utils.js:298:28)
            at new Promise (<anonymous>)
            at callAsyncCircusFn (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/utils.js:231:10)
            at _callCircusTest (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:316:40)
            at async _runTest (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:252:3)
            at async _runTestsForDescribeBlock (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:126:9)
            at async _runTestsForDescribeBlock (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:121:9)
            at async run (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/run.js:71:3)
            at async runAndTransformResultsToJestFormat (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
            at async jestAdapter (/home/runner/work/factory-web/factory-web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:[19](https://github.com/SenraSystems/factory-web/actions/runs/11377342432/job/31651306229?pr=791#step:7:20))
            at async runTestInternal (/home/runner/work/factory-web/factory-web/node_modules/jest-runner/build/runTest.js:367:16)
            at async runTest (/home/runner/work/factory-web/factory-web/node_modules/jest-runner/build/runTest.js:444:34),
        type: 'unhandled exception'
      }

      11 |   it('renders', async () => {
      12 |     const operation = operationFactory.build({ number: 10 });
    > 13 |     render(<OperationForm tenantId={faker.string.uuid()} operation={operation} />);
         |           ^
      14 |     await act(async () => {
      15 |       fireEvent.click(screen.getByText('Edit Operation'));
      16 |     });
```
