### ISSUE TITLE
Failed to resolve import "@/ in the JSX Projects

### ISSUE THREAD

**Issue by pga5e** [chakra-ui/chakra-ui#9407]
### Description

This is my project structure:
```
src/
  assets/
    hero-img-1.png
    hero-img-2.png
  layout/
    Hero.jsx
    ui/
      Carousel.jsx
```

In my my hero.jsx file: `import HeroBGIMG from "@/assets/hero-img.jpg";` lines works perfectly no issues whatsoever

in the one level down carousel.jsx file: `import Hero1 from "@/assets/hero-img-1.png";
import Hero2 from "@/assets/hero-img-2.png"; `

what is worst is that `import Hero1 from "../../assets/hero-img-1.png";
import Hero2 from "../../assets/hero-img-2.png";` are correct but even they dont work

gives me this error: 
```
[plugin:vite:import-analysis] Failed to resolve import "@/assets/hero-img-2.png" from "src/layout/ui/Carousel.jsx". Does the file exist?
E:/Projects ALL/SurajProjects/FruitablesUI/src/layout/ui/Carousel.jsx:3:18
17 |  import { Box, Flex, Image, Button, IconButton } from "@chakra-ui/react";
18 |  import Hero1 from "@/assets/hero-img-1.png";
19 |  import Hero2 from "@/assets/hero-img-2.png";
   |                     ^
20 |  import { BiLeftArrow, BiRightArrow } from "react-icons/bi";
21 |  const Carousel = () => {
    at TransformPluginContext._formatError (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47377:41)
    at TransformPluginContext.error (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47372:16)
    at normalizeUrl (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:45638:23)
    at async file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:45757:39
    at async Promise.all (index 5)
    at async TransformPluginContext.transform (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:45684:7)
    at async EnvironmentPluginContainer.transform (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47219:18)
    at async loadAndTransform (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:41030:27)
    at async viteTransformMiddleware (file:///E:/Projects%20ALL/SurajProjects/FruitablesUI/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:42474:24
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

====================
[plugin:vite:import-analysis] Failed to resolve import "../../assets/hero-img-2.png" from "src/layout/ui/Carousel.jsx". Does the file exist?
```

**This kind of issues only started up after 3.0 Update** there was no such issues in older 2.10.4

here is my jsconfig, vite.config & package.json
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import jsconfigPaths from "vite-jsconfig-paths";

export default defineConfig({
  plugins: [react(), jsconfigPaths()],
});

```
---
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "skipLibCheck": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}

```
---
```
{
  "name": "hihi",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@chakra-ui/react": "^3.2.4",
    "@emotion/react": "^11.14.0",
    "next-themes": "^0.4.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-icons": "^5.4.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.17.0",
    "@types/react": "^18.3.18",
    "@types/react-dom": "^18.3.5",
    "@vitejs/plugin-react": "^4.3.4",
    "eslint": "^9.17.0",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.16",
    "globals": "^15.14.0",
    "vite": "^6.0.5",
    "vite-jsconfig-paths": "^2.0.1"
  }
}

```
---

### Link to Reproduction

https://github.com/pga5e/FruitablesUI/blob/main/src/layout/Hero.jsx

### Steps to reproduce

1. Go to `import Hero1 from "../../assets/hero-img-1.png";` or import Hero1 from "@/assets/hero-img-1.png";
4. See error `[plugin:vite:import-analysis] Failed to resolve import "../../assets/hero-img-2.png" from "src/layout/ui/Carousel.jsx". Does the file exist?`

Yes file exist!!!!!!!!!!!!

### Chakra UI Version

3.2.4

### Browser

131

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by pga5e** [comment]
@segunadebayo if I switched the entire project to 2.10.4 then in the JSX file:
```
import Hero1 from "../../assets/hero-img-1.png";
import Hero2 from "../../assets/hero-img-2.jpg";
```
Works!

Why 3.0 is optimised for TSX and if you try to use it for JSX it fails?

**Comment by segunadebayo** [comment]
Did you try to set up the `vite-tsconfig-paths` instead? I noticed you have `vite-jsconfig-paths`

![CleanShot 2025-01-03 at 12 19 27@2x](https://github.com/user-attachments/assets/16805ab0-96a4-4336-ac9d-185516ef2c53)

I've tested V3  with JSX, and it works pretty well. I will create a sandbox for this and share.
